# configuration
# fill in the course details
 
courseName: QuIP - Quantum Integer Programming

# small title that is at the top of every page
subtitle: 47-779 course syllabus - Fall 2020

# baseurl is the same as the name of the repository
baseurl: /QuIP

# url where the required reading is available to download
docsUrl: "" 

# url where the student's grading info is kept
gradingUrl: "" 

# url where the Github repository is
repoUrl: "https://github.com/bernalde/QuIP"


# change only if you know what you are doing
collections:
  syllabus:
    output: true
defaults:
  - scope:
      path: ""
      type: syllabus
    values:
      layout: unit

theme: jekyll-theme-slate